#!/usr/bin/env python3
"""
apply_migrate_content_patch.py
Patches scripts/publish_github_pages.py so build_migration_page() renders
expanded long-form content (intro, elaborated steps, common challenges,
FAQ) whenever data/cache/migrate_content.json has an entry for that pair —
generated separately by scripts/migrate_content_generator.py.

Also fixes a separate bug found while investigating: migrate-*/index.html
pages currently ship with ZERO AdSense wiring — no google-adsense-account
meta tag, no adsbygoogle script, no ad unit. Every other page type on the
site has this; migrate pages were missed. This patch adds the same
verification meta tag, script snippet, and one in-content ad unit that
comparison pages already use (calling the existing get_adsense_snippet()
and get_adsense_unit() helpers — no new ad code, just wiring up what's
already there). Confirmed via `grep -c adsense` on build_migration_page()
returning 0 before this patch.

Pairs with no cached content yet keep rendering exactly as before (short
version), so this patch is safe to apply and commit before you've
generated any expanded content.

USAGE:
    Save this file in the ROOT of your opensource-alternative-finder repo
    (same folder as scripts/), then run:

        python3 apply_migrate_content_patch.py

    Then rebuild locally to confirm no errors:

        python3 scripts/publish_github_pages.py

Safe to re-run — checks for its own marker before patching and skips if
already applied.
"""
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
TARGET = "scripts/publish_github_pages.py"

IMPORT_OLD = """import json, logging, os, re
from datetime import datetime
from pathlib import Path
from typing import Dict, List
from migration_steps_override import MIGRATION_STEPS_OVERRIDE"""

IMPORT_NEW = """import json, logging, os, re
from datetime import datetime
from pathlib import Path
from typing import Dict, List
from migration_steps_override import MIGRATION_STEPS_OVERRIDE

MIGRATE_CONTENT_CACHE_PATH = Path(__file__).parent.parent / "data" / "cache" / "migrate_content.json"


def load_migrate_content_cache() -> dict:
    \"\"\"Expanded migration-guide content generated by migrate_content_generator.py,
    keyed by '{prop_key}-to-{oss_key}'. Returns {} if the cache doesn't exist yet
    (e.g. before the generator has been run), in which case build_migration_page()
    falls back to the original short-form content.\"\"\"
    if MIGRATE_CONTENT_CACHE_PATH.exists():
        with open(MIGRATE_CONTENT_CACHE_PATH) as f:
            return json.load(f)
    return {}


MIGRATE_CONTENT = load_migrate_content_cache()"""

STEPS_HTML_OLD = """    steps_html = ''
    for i, step in enumerate(steps, 1):
        steps_html += f\"\"\"
    <div class="step-card">
      <div class="step-num">{i}</div>
      <div class="step-text">{step}</div>
    </div>\"\"\"

    oss_website  = AFFILIATE_LINKS.get(oss_key, comp.get('oss_website', '#'))"""

STEPS_HTML_NEW = """    steps_html = ''
    for i, step in enumerate(steps, 1):
        steps_html += f\"\"\"
    <div class="step-card">
      <div class="step-num">{i}</div>
      <div class="step-text">{step}</div>
    </div>\"\"\"

    # -- Expanded long-form content (from migrate_content_generator.py) --
    # Falls back to nothing (original short page) if this pair hasn't been
    # processed by the generator yet.
    expanded = MIGRATE_CONTENT.get(override_key, {})
    expanded_intro_html = ''
    expanded_steps_html = ''
    challenges_html = ''
    faq_html = ''

    if expanded:
        intro_paras = [p.strip() for p in expanded.get('intro', '').split('\\n') if p.strip()]
        expanded_intro_html = ''.join(f'<p style="margin-bottom:1rem;color:var(--text);line-height:1.7;">{p}</p>' for p in intro_paras)

        exp_steps = expanded.get('steps', [])
        if exp_steps:
            rendered = ''
            for i, s in enumerate(exp_steps, 1):
                rendered += f\"\"\"
    <div class="step-card">
      <div class="step-num">{i}</div>
      <div class="step-text"><strong>{s.get('title','')}</strong><br>{s.get('detail','')}</div>
    </div>\"\"\"
            expanded_steps_html = rendered

        challenges = expanded.get('challenges', [])
        if challenges:
            items = ''.join(
                f'<div style="margin-bottom:1rem;"><strong style="color:var(--text);">{c.get("issue","")}</strong><br>'
                f'<span style="color:var(--text-muted);">{c.get("solution","")}</span></div>'
                for c in challenges
            )
            challenges_html = f\"\"\"
  <div class="card">
    <h2>\u26a0\ufe0f Common Challenges & How to Avoid Them</h2>
    {items}
  </div>\"\"\"

        faq = expanded.get('faq', [])
        if faq:
            items = ''.join(
                f'<div style="margin-bottom:1.25rem;"><strong style="color:var(--text);">{qa.get("q","")}</strong><br>'
                f'<span style="color:var(--text-muted);">{qa.get("a","")}</span></div>'
                for qa in faq
            )
            faq_html = f\"\"\"
  <div class="card">
    <h2>\u2753 Frequently Asked Questions</h2>
    {items}
  </div>\"\"\"

    oss_website  = AFFILIATE_LINKS.get(oss_key, comp.get('oss_website', '#'))"""

CONTENT_DIV_OLD = """<div class="content">
  <div class="savings-box">
    <div class="amount">$0</div>
    <div class="desc">
      <strong>{oss_name} is free to self-host</strong> \u2014 vs {comp.get('proprietary_pricing','paid')} for {prop_name}.<br>
      For a 50-person team that's a significant annual saving.
    </div>
  </div>
  <div class="card">
    <h2>\U0001f5fa\ufe0f Migration Steps</h2>
    {steps_html}
  </div>
  <div class="card">
    <h2>\U0001f517 Get Started</h2>
    <div class="tool-links">
      <a class="tool-link leave" href="{prop_website}" target="_blank" rel="noopener">Export from {prop_name} \u2192</a>
      <a class="tool-link join" href="{oss_website}" target="_blank" rel="noopener">Set up {oss_name} \u2192</a>
    </div>
  </div>
  <div class="card" style="text-align:center;padding:1.5rem;">
    <p style="color:var(--text-muted);font-size:0.9rem;margin-bottom:1rem;">Want a full feature and pricing comparison before you switch?</p>
    <a class="back-btn" href="../{comp_slug}/">Read the Full {prop_name} vs {oss_name} Comparison \u2192</a>
  </div>
</div>"""

CONTENT_DIV_NEW = """<div class="content">
  {f'<div class="card">{expanded_intro_html}</div>' if expanded_intro_html else ''}
  <div class="savings-box">
    <div class="amount">$0</div>
    <div class="desc">
      <strong>{oss_name} is free to self-host</strong> \u2014 vs {comp.get('proprietary_pricing','paid')} for {prop_name}.<br>
      For a 50-person team that's a significant annual saving.
    </div>
  </div>
  <div class="card">
    <h2>\U0001f5fa\ufe0f Migration Steps</h2>
    {expanded_steps_html if expanded_steps_html else steps_html}
  </div>
  {challenges_html}
  <div class="card">
    <h2>\U0001f517 Get Started</h2>
    <div class="tool-links">
      <a class="tool-link leave" href="{prop_website}" target="_blank" rel="noopener">Export from {prop_name} \u2192</a>
      <a class="tool-link join" href="{oss_website}" target="_blank" rel="noopener">Set up {oss_name} \u2192</a>
    </div>
  </div>
  {faq_html}
  <div class="card" style="text-align:center;padding:1.5rem;">
    <p style="color:var(--text-muted);font-size:0.9rem;margin-bottom:1rem;">Want a full feature and pricing comparison before you switch?</p>
    <a class="back-btn" href="../{comp_slug}/">Read the Full {prop_name} vs {oss_name} Comparison \u2192</a>
  </div>
</div>"""


HEAD_OLD = """    html = f\"\"\"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{seo_title}</title>
  <meta name="description" content="{seo_desc}">
  <meta name="keywords" content="migrate {prop_name} to {oss_name}, {prop_name} to {oss_name} migration, how to switch from {prop_name}, {oss_name} migration guide">
  <link rel="canonical" href="{canonical}">
  <meta name="robots" content="index, follow">
  <meta property="og:type" content="article">
  <meta property="og:title" content="{seo_title}">
  <meta property="og:description" content="{seo_desc}">
  <meta property="og:url" content="{canonical}">
  <script type="application/ld+json">"""

HEAD_NEW = """    html = f\"\"\"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{seo_title}</title>
  <meta name="description" content="{seo_desc}">
  <meta name="keywords" content="migrate {prop_name} to {oss_name}, {prop_name} to {oss_name} migration, how to switch from {prop_name}, {oss_name} migration guide">
  <link rel="canonical" href="{canonical}">
  <meta name="robots" content="index, follow">
  <meta name="google-adsense-account" content="ca-pub-4633315697698743">
  <meta property="og:type" content="article">
  <meta property="og:title" content="{seo_title}">
  <meta property="og:description" content="{seo_desc}">
  <meta property="og:url" content="{canonical}">
  {get_adsense_snippet()}
  <script type="application/ld+json">"""

ADUNIT_OLD = """  <div class="card">
    <h2>\U0001f5fa\ufe0f Migration Steps</h2>
    {expanded_steps_html if expanded_steps_html else steps_html}
  </div>
  {challenges_html}"""

ADUNIT_NEW = """  <div class="card">
    <h2>\U0001f5fa\ufe0f Migration Steps</h2>
    {expanded_steps_html if expanded_steps_html else steps_html}
  </div>
  {get_adsense_unit()}
  {challenges_html}"""


def main():
    path = os.path.join(ROOT, TARGET)
    if not os.path.exists(path):
        print(f"ERROR: {TARGET} not found. Run this from the repo root.")
        sys.exit(1)

    with open(path) as f:
        src = f.read()

    if "MIGRATE_CONTENT_CACHE_PATH" in src:
        print(f"SKIP: {TARGET} already patched.")
        return

    for label, old, new in [
        ("imports + cache loader", IMPORT_OLD, IMPORT_NEW),
        ("expanded content builder", STEPS_HTML_OLD, STEPS_HTML_NEW),
        ("content div rendering", CONTENT_DIV_OLD, CONTENT_DIV_NEW),
        ("AdSense head tags (previously missing entirely)", HEAD_OLD, HEAD_NEW),
        ("AdSense in-content ad unit (previously missing entirely)", ADUNIT_OLD, ADUNIT_NEW),
    ]:
        if old not in src:
            print(f"ERROR: could not find the expected '{label}' block — your file may already "
                  f"differ from what this patch expects. No changes written.")
            sys.exit(1)
        if src.count(old) > 1:
            print(f"ERROR: the '{label}' block appears more than once — refusing to guess. No changes written.")
            sys.exit(1)
        src = src.replace(old, new)
        print(f"Patched: {label}")

    with open(path, "w") as f:
        f.write(src)

    print(f"\nDone. {TARGET} now renders expanded content when data/cache/migrate_content.json has it.")
    print("Next: run scripts/migrate_content_generator.py to populate that cache.")


if __name__ == "__main__":
    main()
